import { About } from './components/About';
import { ConfigPanel } from './components/ConfigPanel';
import { DatasetPanel } from './components/DatasetPanel';
import { HistoryPanel } from './components/HistoryPanel';
import { ManifestPanel } from './components/ManifestPanel';
import { MetricsPanel } from './components/MetricsPanel';
import { ModeSelector } from './components/ModeSelector';
import { APP_VERSION, defaultConfig, defaultParameters, loadCatalog, modelLabels } from './data/catalog';
import { profileCsv } from './lib/duckdb';
import { sha256 } from './lib/hash';
import { runInPyodide } from './lib/pyodideClient';
import { computeReproducibilityScore, finalizeManifest } from './lib/reproducibility';
import { clearHistory, loadHistory, saveHistory } from './lib/storage';
import type { DatasetEntry, DatasetProfile, ExperimentConfig, ExperimentManifest, ModelResult } from './types';
import { Activity, Beaker, BookOpenCheck, Database, Github, History, Info, Play, ShieldCheck, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

type Tab='lab'|'history'|'about';
type StaticFixture={datasetId:string;task:ExperimentConfig['task'];modelKey:ExperimentConfig['modelKey'];seed:number;testSize:number;parameters:Record<string,unknown>;metrics:Record<string,number|null>;confusionMatrix?:number[][]|null;runtime:Record<string,string>;note:string};

export default function App(){
 const [tab,setTab]=useState<Tab>('lab'); const [datasets,setDatasets]=useState<DatasetEntry[]>([]); const [config,setConfig]=useState<ExperimentConfig>(defaultConfig);
 const [csvText,setCsvText]=useState(''); const [customDataset,setCustomDataset]=useState<DatasetEntry|null>(null); const [profile,setProfile]=useState<DatasetProfile|null>(null);
 const [results,setResults]=useState<ModelResult[]>([]); const [winner,setWinner]=useState<ExperimentConfig['modelKey']>(); const [manifest,setManifest]=useState<ExperimentManifest|null>(null);
 const [history,setHistory]=useState<ExperimentManifest[]>(loadHistory); const [status,setStatus]=useState('Ready'); const [running,setRunning]=useState(false); const [error,setError]=useState('');
 const allDatasets=useMemo(()=>customDataset?[customDataset,...datasets]:datasets,[datasets,customDataset]); const dataset=allDatasets.find(d=>d.id===config.datasetId);
 useEffect(()=>{loadCatalog().then(setDatasets).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!dataset||!dataset.file)return;fetch(`${import.meta.env.BASE_URL}${dataset.file}`).then(r=>r.text()).then(setCsvText).catch(e=>setError(String(e)))},[dataset?.id]);
 const changeConfig=(next:ExperimentConfig)=>{if(next.mode==='static'){next={...next,strategy:'single',seed:42,testSize:.25,parameters:defaultParameters[next.modelKey]}}setConfig(next);setResults([]);setManifest(null);};
 const upload=async(file:File)=>{const text=await file.text();const header=text.split(/\r?\n/,1)[0]?.split(',')??[];const hash=await sha256(text);const entry:DatasetEntry={id:`upload-${hash.slice(0,10)}`,name:file.name.replace(/\.csv$/i,''),version:'user-upload',task:config.task,target:header.at(-1)??'target',file:'',rows:Math.max(0,text.split(/\r?\n/).filter(Boolean).length-1),columns:header.length,sha256:hash,description:'User-provided CSV. The file remains in this browser session.'};setCustomDataset(entry);setCsvText(text);setConfig({...config,mode:'full',strategy:'single',datasetId:entry.id,target:entry.target});setResults([]);setManifest(null);};
 const run=async()=>{if(!dataset||!csvText)return;setRunning(true);setError('');setProfile(null);setResults([]);setManifest(null);try{
   setStatus(config.mode==='full'?'Computing SHA-256 and profiling with DuckDB-WASM…':'Verifying the versioned reference dataset…'); const actualHash=await sha256(csvText); const prof=config.mode==='full'?await profileCsv(csvText):{rows:dataset.rows,columns:dataset.columns,columnProfiles:[],duckdbVersion:'not-loaded'};setProfile(prof);
   let runResults:ModelResult[]=[];let selected=config.modelKey;let runtime:any={mode:'static-reference',app:APP_VERSION,duckdbWasm:prof.duckdbVersion};
   if(config.mode==='static'){setStatus('Loading versioned reference fixture…');const fixtures:StaticFixture[]=await fetch(`${import.meta.env.BASE_URL}fixtures/static-runs.json`).then(r=>r.json());const fixture=fixtures.find(f=>f.datasetId===dataset.id&&f.modelKey===config.modelKey);if(!fixture)throw new Error('No static reference fixture exists for this dataset/model pair.');runResults=[{modelKey:fixture.modelKey,label:modelLabels[fixture.modelKey],metrics:fixture.metrics,confusionMatrix:fixture.confusionMatrix}];runtime={...runtime,...fixture.runtime};selected=fixture.modelKey;}
   else {const response=await runInPyodide({id:crypto.randomUUID(),csvText,config,dataset:{name:dataset.name,version:dataset.version,sha256:actualHash}},setStatus);runResults=response.results;selected=response.winner??config.modelKey;runtime={...response.runtime,duckdbWasm:prof.duckdbVersion};}
   setResults(runResults);setWinner(selected); const score=computeReproducibilityScore({seed:config.seed,datasetVersion:dataset.version,datasetHash:actualHash,parameters:config.parameters,metricsCount:Object.keys(runResults[0]?.metrics??{}).length,runtimeKnown:true});
   const complete=await finalizeManifest({schemaVersion:'1.0.0',createdAt:new Date().toISOString(),reproducibilityScore:score,mode:config.mode,strategy:config.strategy,seed:config.seed,dataset:{id:dataset.id,name:dataset.name,version:dataset.version,sha256:actualHash,rows:prof.rows,columns:prof.columns,target:config.target,source:customDataset?.id===dataset.id?'upload':'bundled'},task:config.task,selectedModel:config.modelKey,parameters:config.parameters,testSize:config.testSize,results:runResults,winner:selected,runtime:{...runtime,app:APP_VERSION},codeFingerprint:'automl-hub-pipeline-v1',notes:[config.mode==='static'?'Static reference: no model was executed.':'Full browser execution completed in Pyodide.','Matching seeds improve repeatability but do not guarantee bit-identical floating-point results across every runtime.']});
   setManifest(complete);const next=[complete,...history.filter(h=>h.experimentId!==complete.experimentId)].slice(0,20);setHistory(next);saveHistory(next);setStatus('Experiment complete. Manifest fingerprint created.');
 }catch(e){setError(e instanceof Error?e.message:String(e));setStatus('Run failed.')}finally{setRunning(false)}};
 const loadManifest=(m:ExperimentManifest)=>{setTab('lab');setConfig({...config,mode:m.mode,strategy:m.strategy,datasetId:m.dataset.id,task:m.task,target:m.dataset.target,modelKey:m.selectedModel,seed:m.seed,testSize:m.testSize,parameters:m.parameters as Record<string,number|string|boolean|null>});setManifest(m);setResults(m.results);setWinner(m.winner);};
 return <div className="app-shell"><header className="site-header"><a className="brand" href="#top"><span><Beaker/></span><div><b>AutoML Reproducibility Hub</b><small>Seeded · Versioned · Inspectable</small></div></a><nav><button className={tab==='lab'?'active':''} onClick={()=>setTab('lab')}><Activity/> Lab</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}><History/> History</button><button className={tab==='about'?'active':''} onClick={()=>setTab('about')}><Info/> About</button></nav><a className="github-button" href="https://github.com/FaramarzKowsari/automl-reproducibility-hub" target="_blank" rel="noreferrer"><Github/> GitHub</a></header>
 <main id="top">{tab==='lab'&&<><section className="hero"><div><span className="eyebrow"><Sparkles/> Browser-native research software</span><h1>Reproduce the experiment, not just the score.</h1><p>Bind every machine-learning result to its seed, exact dataset version, SHA-256 fingerprint, preprocessing contract, model parameters, metrics, and runtime versions.</p><div className="hero-badges"><span><ShieldCheck/> No server</span><span><Database/> DuckDB-WASM</span><span><BookOpenCheck/> Pyodide + scikit-learn</span></div></div><div className="manifest-visual"><code>seed: 42</code><code>dataset: conversion@1.0.0</code><code>sha256: verified</code><code>parameters: explicit</code><code>metrics: versioned</code></div></section>
 <ModeSelector mode={config.mode} onChange={mode=>changeConfig({...config,mode})}/><section className="lab-grid"><ConfigPanel config={config} datasets={allDatasets} onChange={changeConfig} disabled={running}/><DatasetPanel dataset={dataset} profile={profile} onUpload={upload}/></section><div className="run-bar"><div><b>{status}</b><span>{config.mode==='full'?'Full mode runs Python and SQL in your browser.':'Static mode presents a labeled, precomputed reference run.'}</span></div><button className="run-button" onClick={run} disabled={running||!dataset}><Play/>{running?'Running…':'Run reproducible experiment'}</button></div>{error&&<div className="error-box">{error}</div>}<MetricsPanel results={results} winner={winner} task={config.task}/><ManifestPanel manifest={manifest}/></>}
 {tab==='history'&&<HistoryPanel items={history} onLoad={loadManifest} onClear={()=>{clearHistory();setHistory([])}}/>}{tab==='about'&&<About/>}</main><footer><div><b>AutoML Reproducibility Hub</b><span>Open-source research software by Faramarz Kowsari</span></div><div><a href="https://orcid.org/0000-0003-1692-0453">ORCID</a><a href="https://FaramarzKowsari.github.io">Website</a><a href="https://github.com/FaramarzKowsari">GitHub</a></div></footer></div>;
}
